# Generated by Django 4.2.16 on 2026-02-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_client__902c52_idx',
            old_name='leads_lead_client__363fe4_idx',
        ),
    ]
