# Generated by Django 4.2.16 on 2026-02-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_localization'),
        ('leads', '0002_rename_leads_lead_client__363fe4_idx_leads_lead_client__902c52_idx'),
    ]

    operations = [
    ]
