# Generated by Django 4.2.16 on 2026-02-12

from django.db import migrations, models
import re


ISO_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
PHONE_RE = re.compile(r"^\+?[0-9\s\-()]{7,20}$")


def normalize_phone(value):
    if value is None:
        return None
    phone = str(value).strip()
    if not phone:
        return None
    if ISO_DATE_RE.fullmatch(phone):
        return None
    if not PHONE_RE.fullmatch(phone):
        return None
    digits = re.sub(r"\D", "", phone)
    if len(digits) < 7:
        return None
    return phone


def cleanup_phone_values(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    for lead in Lead.objects.all().only("id", "phone"):
        normalized = normalize_phone(lead.phone)
        if lead.phone != normalized:
            Lead.objects.filter(id=lead.id).update(phone=normalized)


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_merge_20260212_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Телефон"),
        ),
        migrations.RunPython(cleanup_phone_values, migrations.RunPython.noop),
    ]
