# Generated by Django 4.2.16 on 2026-02-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='analytics_a_client__b53cc8_idx',
            old_name='analytics_a_client__fe5f61_idx',
        ),
    ]
