# Generated by Django 4.2.16 on 2026-02-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_localization'),
        ('analytics_app', '0002_rename_analytics_a_client__fe5f61_idx_analytics_a_client__b53cc8_idx'),
    ]

    operations = [
    ]
