# Generated by Django 4.2.16 on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_alter_client_options_alter_client_api_key_and_more"),
        ("analytics_app", "0003_merge_20260212_1711"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(db_index=True, max_length=64, verbose_name="Session ID")),
                ("url", models.URLField(max_length=1000, verbose_name="URL страницы")),
                ("pathname", models.CharField(db_index=True, max_length=512, verbose_name="Pathname")),
                ("query_string", models.TextField(blank=True, null=True, verbose_name="Query string")),
                ("referrer", models.URLField(blank=True, max_length=1000, null=True, verbose_name="Referrer")),
                ("utm_source", models.CharField(blank=True, max_length=255, null=True, verbose_name="UTM Source")),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True, verbose_name="UTM Medium")),
                ("utm_campaign", models.CharField(blank=True, max_length=255, null=True, verbose_name="UTM Campaign")),
                ("utm_term", models.CharField(blank=True, max_length=255, null=True, verbose_name="UTM Term")),
                ("utm_content", models.CharField(blank=True, max_length=255, null=True, verbose_name="UTM Content")),
                ("max_scroll_depth", models.PositiveSmallIntegerField(default=0, verbose_name="Макс. глубина скролла")),
                ("duration_seconds", models.PositiveIntegerField(default=0, verbose_name="Время на странице (сек.)")),
                ("attributed_leads", models.PositiveIntegerField(default=0, verbose_name="Атрибутированные лиды")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр страницы",
                "verbose_name_plural": "Просмотры страниц",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(db_index=True, max_length=64, verbose_name="Session ID")),
                ("page_pathname", models.CharField(db_index=True, max_length=512, verbose_name="Страница")),
                ("element_text", models.CharField(blank=True, default="", max_length=100, verbose_name="Текст элемента")),
                ("element_id", models.CharField(blank=True, default="", max_length=255, verbose_name="ID элемента")),
                ("element_class", models.CharField(blank=True, default="", max_length=255, verbose_name="Класс элемента")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_events",
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клик",
                "verbose_name_plural": "Клики",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(fields=["client", "session_id", "created_at"], name="analytics_a_client__bf9074_idx"),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(fields=["client", "pathname", "created_at"], name="analytics_a_client__fd0fce_idx"),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(fields=["client", "created_at"], name="analytics_a_client__7febe8_idx"),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(fields=["client", "page_pathname", "created_at"], name="analytics_a_client__4f3068_idx"),
        ),
    ]
