# Generated by Django 4.2.16 on 2026-02-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0004_pageview_clickevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clickevent',
            new_name='analytics_a_client__f7943d_idx',
            old_name='analytics_a_client__7febe8_idx',
        ),
        migrations.RenameIndex(
            model_name='clickevent',
            new_name='analytics_a_client__57c4d4_idx',
            old_name='analytics_a_client__4f3068_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='analytics_a_client__df9df5_idx',
            old_name='analytics_a_client__bf9074_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='analytics_a_client__949553_idx',
            old_name='analytics_a_client__fd0fce_idx',
        ),
    ]
