# Generated by Django 4.2.16 on 2026-02-14 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_options_alter_client_api_key_and_more'),
        ('analytics_app', '0006_visitor_id_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickevent',
            options={'ordering': ('-created_at',), 'verbose_name': 'Click', 'verbose_name_plural': 'Clicks'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created_at',), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ('-created_at',), 'verbose_name': 'Page view', 'verbose_name_plural': 'Page views'},
        ),
        migrations.RenameIndex(
            model_name='clickevent',
            new_name='analytics_a_client__785b72_idx',
            old_name='analytics_a_client__visitor_clk_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='analytics_a_client__b04d8a_idx',
            old_name='analytics_a_client__visitor_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='pageview',
            new_name='analytics_a_client__aea0bc_idx',
            old_name='analytics_a_client__visitor_pv_idx',
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='element_class',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Element class'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='element_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Element ID'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='element_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Element text'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='page_pathname',
            field=models.CharField(db_index=True, max_length=512, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='element_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Element ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('click', 'Click'), ('form_submit', 'Form submit')], max_length=20, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='page_url',
            field=models.URLField(max_length=1000, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='attributed_leads',
            field=models.PositiveIntegerField(default=0, verbose_name='Attributed leads'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Time on page (sec)'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='max_scroll_depth',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Max scroll depth'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='Page URL'),
        ),
    ]
