# Generated by Django 4.2.16 on 2026-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramupdatelog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Лог Telegram', 'verbose_name_plural': 'Логи Telegram'},
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='chat_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название чата'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='chat_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип чата'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='command',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='message_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID сообщения'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Полные данные'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='update_id',
            field=models.BigIntegerField(db_index=True, verbose_name='ID обновления'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
    ]
