# Generated by Django 4.2.16 on 2026-02-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_audit', '0003_siteseoaudit_used_sitemap_and_sitemap_urls_count'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seopage',
            new_name='seo_audit_s_audit_i_15cee6_idx',
            old_name='seo_audit_s_audit_i_4e9b6c_idx',
        ),
        migrations.AlterField(
            model_name='seoissue',
            name='issue_type',
            field=models.CharField(choices=[('missing_title', 'missing_title'), ('bad_title_length', 'bad_title_length'), ('title_too_short', 'title_too_short'), ('title_too_long', 'title_too_long'), ('missing_description', 'missing_description'), ('description_too_short', 'description_too_short'), ('description_too_long', 'description_too_long'), ('duplicate_title', 'duplicate_title'), ('missing_h1', 'missing_h1'), ('multiple_h1', 'multiple_h1'), ('long_h1', 'long_h1'), ('heading_hierarchy_gap', 'heading_hierarchy_gap'), ('low_word_count', 'low_word_count'), ('image_missing_alt', 'image_missing_alt'), ('image_empty_alt', 'image_empty_alt'), ('bad_status', 'bad_status'), ('network_error', 'network_error'), ('redirect', 'redirect'), ('slow_response', 'slow_response'), ('large_page_size', 'large_page_size'), ('missing_canonical', 'missing_canonical'), ('missing_meta_robots', 'missing_meta_robots'), ('missing_viewport', 'missing_viewport'), ('missing_charset', 'missing_charset'), ('missing_robots_txt', 'missing_robots_txt'), ('robots_disallow_all', 'robots_disallow_all'), ('robots_missing_sitemap', 'robots_missing_sitemap'), ('missing_sitemap', 'missing_sitemap'), ('bad_sitemap_status', 'bad_sitemap_status'), ('sitemap_mismatch', 'sitemap_mismatch')], max_length=64),
        ),
        migrations.AlterField(
            model_name='seoissue',
            name='severity',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Критичная')], max_length=16),
        ),
        migrations.AlterField(
            model_name='siteseoaudit',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('done', 'Готово'), ('error', 'Ошибка'), ('stopped', 'Остановлено')], db_index=True, default='pending', max_length=16),
        ),
    ]
