# Generated by Django 5.0.14 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_audit", "0005_siteseoaudit_performance_and_indexing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="seopage",
            name="commercial_readiness_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="seopage",
            name="commercial_status",
            field=models.CharField(
                choices=[
                    ("good", "Ready for leads"),
                    ("warning", "Needs improvement"),
                    ("critical", "Weak conversion readiness"),
                ],
                default="warning",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="seopage",
            name="has_benefits_block",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seopage",
            name="has_cta",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seopage",
            name="has_faq",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seopage",
            name="has_form",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seopage",
            name="has_messenger",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seopage",
            name="has_offer_like_heading",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seopage",
            name="has_phone_or_contact",
            field=models.BooleanField(default=False),
        ),
    ]
