# Generated by Django 5.0.14 on 2026-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_audit", "0006_seopage_commercial_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="seopage",
            name="commercial_signals_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="seopage",
            name="conversion_path_type",
            field=models.CharField(
                choices=[
                    ("none", "No conversion path"),
                    ("form", "Form"),
                    ("contacts", "Direct contacts"),
                    ("messenger", "Messenger or social contact"),
                    ("widget", "Widget"),
                    ("mixed", "Mixed conversion mechanics"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="seopage",
            name="has_conversion_path",
            field=models.BooleanField(default=False),
        ),
    ]
