# Generated by Django 4.2.16 on 2026-04-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_audit', '0007_seopage_conversion_path_and_signals_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoissue',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='indexability_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('indexable', 'Indexable'), ('noindex', 'Noindex'), ('blocked', 'Blocked by robots.txt'), ('conflict', 'Indexability conflict')], default='unknown', max_length=24),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='speed_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='siteseoaudit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error'), ('stopped', 'Stopped')], db_index=True, default='pending', max_length=16),
        ),
    ]
