# Generated by Django 4.2.16 on 2026-02-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_delivery_channels_and_telegram_link'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportlog',
            new_name='reports_rep_client__cef9a3_idx',
            old_name='reports_rep_client__9f4e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='reportlog',
            new_name='reports_rep_client__4fba23_idx',
            old_name='reports_rep_client__4a6cab_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramlinktoken',
            new_name='reports_tel_code_457555_idx',
            old_name='reports_tel_code_2e56d0_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramlinktoken',
            new_name='reports_tel_client__ecaa3d_idx',
            old_name='reports_tel_client_c4d19a_idx',
        ),
    ]
