# Generated by Django 4.2.16 on 2026-05-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('about', 'О компании'), ('services', 'Услуги'), ('reviews', 'Отзывы'), ('gallery', 'Галерея'), ('contacts', 'Контакты')], max_length=100, verbose_name='Тип секции'),
        ),
    ]
