# Generated by Django 4.2.16 on 2026-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_sitesection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesection',
            name='component_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ключ компонента'),
        ),
        migrations.AddField(
            model_name='sitesection',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки секции'),
        ),
    ]
