# Generated by Django 4.2.16 on 2026-05-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_sitesection_component_key_sitesection_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='seo',
            field=models.JSONField(blank=True, default=dict, verbose_name='SEO настройки'),
        ),
    ]
