# Generated by Django 4.2.16 on 2026-05-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesection',
            name='seo',
            field=models.JSONField(blank=True, default=dict, verbose_name='SEO settings'),
        ),
    ]
