# Generated by Django 4.2.16 on 2026-05-24 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0006_sectionschema_refactor_sitesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='site',
            name='seo',
            field=models.JSONField(blank=True, default=dict, verbose_name='SEO settings'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Site slug'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='component_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='Component key'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='content',
            field=models.JSONField(blank=True, default=dict, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='Field schema'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Section settings'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Section title'),
        ),
    ]
