# Generated by Django 4.2.30 on 2026-05-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_site_options_alter_site_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(blank=True, max_length=100, verbose_name='Ключ секции')),
                ('form_name', models.CharField(blank=True, max_length=255, verbose_name='Название формы')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('service_type', models.CharField(blank=True, max_length=100, verbose_name='Тип услуги')),
                ('service_title', models.CharField(blank=True, max_length=255, verbose_name='Название услуги')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник (URL)')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена'), ('archived', 'Архив')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'status', 'created_at'], name='sites_sitel_site_id_db4bb5_idx'), models.Index(fields=['service_type'], name='sites_sitel_service_d89535_idx')],
            },
        ),
    ]
