# Generated by Django 4.2.16 on 2026-06-05 13:44

import apps.sites.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0009_site_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name'], 'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
        migrations.AddField(
            model_name='site',
            name='send_to_telegram',
            field=models.BooleanField(default=False, verbose_name='Отправлять заявки в Telegram'),
        ),
        migrations.AddField(
            model_name='site',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ID чата Telegram'),
        ),
        migrations.AddField(
            model_name='site',
            name='telegram_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telegram подключен'),
        ),
        migrations.AlterField(
            model_name='site',
            name='api_key',
            field=models.CharField(default=apps.sites.models.generate_api_key, editable=False, max_length=128, unique=True, verbose_name='Ключ аналитики'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(blank=True, max_length=255, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='site',
            name='seo',
            field=models.JSONField(blank=True, default=dict, verbose_name='SEO-настройки'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug сайта'),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
