# Generated by Django 4.2.30 on 2026-05-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pageview',
            new_name='analytics_p_visit_i_619245_idx',
            old_name='analytics_p_visit_i_415ecc_idx',
        ),
        migrations.RenameIndex(
            model_name='trackingevent',
            new_name='analytics_t_visit_i_64ed02_idx',
            old_name='analytics_t_visit_i_79b319_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='analytics_v_site_id_eab785_idx',
            old_name='analytics_v_site_id_0b8cd8_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='analytics_v_site_id_b22556_idx',
            old_name='analytics_v_site_id_3d6b7d_idx',
        ),
    ]
