# Generated by Django 4.2.16 on 2026-02-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_visit_visitor_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visit',
            new_name='tracker_vis_site_id_bce6b5_idx',
            old_name='tracker_vis_site_id_visitor_idx',
        ),
    ]
