# Generated by Django 4.2.16 on 2026-06-05 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_visit_is_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Событие трекера', 'verbose_name_plural': 'События трекера'},
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Просмотр страницы трекера', 'verbose_name_plural': 'Просмотры страниц трекера'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('-created_at',), 'verbose_name': 'Сайт трекера', 'verbose_name_plural': 'Сайты трекера'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-started_at',), 'verbose_name': 'Визит трекера', 'verbose_name_plural': 'Визиты трекера'},
        ),
        migrations.AlterField(
            model_name='event',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=64, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.visit', verbose_name='Визит'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время просмотра'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.TextField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='tracker.visit', verbose_name='Визит'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='site',
            name='token',
            field=models.CharField(db_index=True, default=tracker.models.generate_site_token, max_length=128, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Браузер'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser_family',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Семейство браузера'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device_type',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание визита'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_ios_browser',
            field=models.BooleanField(default=False, verbose_name='iOS-браузер'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ОС'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referrer',
            field=models.TextField(blank=True, default='', verbose_name='Источник перехода'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='session_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='ID сессии'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tracker.site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало визита'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID посетителя'),
        ),
    ]
