# Generated by Django 4.2.16 on 2026-05-16 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='site_media/%Y/%m/', verbose_name='Файл')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Тип файла')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'ordering': ['-created_at'],
            },
        ),
    ]
