# Generated by Django 4.2.16 on 2026-05-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='MIME-тип'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер (байт)'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
    ]
